---
- name: elvm module
  hosts: elvm
  become: yes
  tasks: 
    - name: Download docker script
      get_url:
        url: https://get.docker.com 
        dest: /tmp/install-docker.sh
        mode: 0777
    - name: Docker setup
      command: "sh /tmp/install-docker.sh --dry-run; sh /tmp/install-docker.sh; "
      become: yes
      register: command_result
    - debug:
        msg: "{{ command_result.stdout_lines }}"
