---
- name: "elvm module docker"
  hosts: elvm
  tasks:

  - name: "Shell"
    shell: |       
      echo "#!/bin/bash"
      echo "curl -fsSL https://get.docker.com -o install-docker.sh" >> ./docker.sh
      echo "sh install-docker.sh --dry-run" >> ./docker.sh
      echo "sh install-docker.sh" >> ./docker.sh
      #chown "${USER:=$(/usr/bin/id -run)}:$USER" ./tets1.txt
      chown "igor:igor" ./docker.sh
      chmod +x ./docker.sh
      sh ./docker.sh
      rm ./docker.sh
    become: yes
    register: result2

