---
- name: elvm module
  hosts: elvm
  become: yes
  tasks:   
  - name: Creates directory config
    file:
      path: /home/{{ lookup('env','USER') }}/{{item}}
      owner: "{{ lookup('env','USER') }}" 
      group: "{{ lookup('env','USER') }}"
      mode: 0755 
      state: directory 
    with_items:
    - 'test'
    #- 'init'
    #- 'dump'
    #- 'log'     

  - name: "Install aptitude"
    apt:
      name: aptitude
      state: latest
      update_cache: true
 
  - name: "Install python3"
    apt:
      pkg:
       - python3
       - software-properties-common
       - python3-pip
       - virtualenv
       - python3-setuptools
      state: latest
      update_cache: true    

  - name: "Install xrdp - xfce4 "
    apt:
      pkg:
      # - guake
      # - xrdp
      # - xfce4
      # - xdm
      # - xfce4-xkb-plugin
      state: latest
      update_cache: true

  - name: "Install ufw"
    apt:
      pkg:
       - ufw
      state: latest
      update_cache: true

  - name:  "ufw allow"
    shell: "ufw allow 22 && ufw status"
    register: command_result
    args:
      chdir: /tmp

  - name:  "shell"
    become: true
    shell: "curl -fsSL https://get.docker.com -o install-docker.sh && sh install-docker.sh --dry-run && sh install-docker.sh"
    register: command_result
    args:
      chdir: /tmp



#  - name: copy file "conf-server_id.cnf"  
#    copy:
#      src: config/conf-server_id.cnf
#      dest: /tmp/docker/config/my.cnf
#      mode: '0644'
#      owner: "{{ lookup('env','USER') }}" 
#      group: "{{ lookup('env','USER') }}"
    
#  - name: copy file "set-permission.sql""  
#    copy:
#      src: config/set-permission.sql
#      dest: /tmp/docker/init/set-permission.sql
#      mode: '0644'
#      owner: "{{ lookup('env','USER') }}" 
#      group: "{{ lookup('env','USER') }}"
    
#  - name: copy  file "docker-compose.yml"
#    copy:
#      src: config/docker-compose.yml
#      dest: /tmp/docker/docker-compose.yml
#      mode: '0644'
#      owner: "{{ lookup('env','USER') }}" 
#      group: "{{ lookup('env','USER') }}"
            
#############################################################
#  - name:  "docker master compose command_result"
#   # become: true
#    shell: "docker compose down -v  && docker compose up -d && docker ps -a "
#    register: command_result
#    args:
#      chdir: /tmp/docker

#############################################################
#  - debug:
#      msg: "{{ command_result.stdout_lines }}"
