---
- name: "elvm module Web-server nginx"
  hosts: elvm
  tasks:

  - name: "Install the package nginx"
    apt: name=nginx state=present
    become: yes
    register: result1

  - name: "Start Nginx Services"
    service: name=nginx state=started
    become: yes
    register: result2
