---
- name: "elvm module Nginx Services"
  hosts: elvm
  tasks:

  - name: "Stop Nginx Services"
    service: name=nginx state=stopped
    become: yes
    register: result2

  - name: "UnInstall the package nginx"
    apt: name=nginx state=absent
    become: yes
    register: result1
